### ISSUE TITLE
[BE] yml 내 커스텀 컴포넌트 이름를 수정해요:)

### ISSUE THREAD

**Issue by ikjo39** [woowacourse-teams/2024-momo#153]
## 이슈 요약

SpringBoot Docs에서 커스텀으로 생성한 yml의 key의 표기를 케밥케이스(`secret-key`)로 권장한다 합니다. 
(아래 링크 참고)
```yaml
security:
  jwt:
#   secret_key: ${random.value}"   X
    secret-key: ${random.value}"
```
이로 인해 스네이크 표기법으로 표기되어 있던 yml의  커스텀 key를 케밥 케이스 형시으로 수정하려 합니다.
## 상세 작업 내용

- [x] 서브 모듈 내 스네이크 표기법 수정
- [x] backend 모듈 내 스네이크 표기법 수정

## 레퍼런스

[configuration-properties.vs-value - SpringBoot docs](https://docs.spring.io/spring-boot/reference/features/external-config.html#features.external-config.typesafe-configuration-properties.vs-value-annotation:~:text=If%20you%20do%20want,would%20not%20be%20considered.)
